/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package papi_costic;

import java.awt.event.KeyAdapter;

import papi_costic.resource.PapiCosticInputKeyAdapter;
import papi_costic.resource.PapiCosticResource;

/**
 * this class is a panel used to display the PAPI Costic form
 * 
 * @author Trustacean
 */
public class PapiCosticForm extends javax.swing.JPanel {

    /**
     * Creates new form PapiCosticForm
     */
    public PapiCosticForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        judulPanel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        masukanPanel = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        tglLahirLabel = new javax.swing.JLabel();
        tglLahirInput = new com.toedter.calendar.JDateChooser();
        tglTesLabel = new javax.swing.JLabel();
        tglTesInput = new com.toedter.calendar.JDateChooser();
        pendidikanLabel = new javax.swing.JLabel();
        pendidikanInput = new javax.swing.JTextField();
        kelaminLabel = new javax.swing.JLabel();
        kelaminInput = new javax.swing.JComboBox<>();
        tujuanLabel = new javax.swing.JLabel();
        tujuanInput = new javax.swing.JTextField();
        papiInputContainer = new javax.swing.JPanel();
        papiInputPanel = new javax.swing.JPanel();
        gLabel = new javax.swing.JLabel();
        gInput = new javax.swing.JTextField();
        lLabel = new javax.swing.JLabel();
        lInput = new javax.swing.JTextField();
        iLabel = new javax.swing.JLabel();
        iInput = new javax.swing.JTextField();
        tLabel = new javax.swing.JLabel();
        tInput = new javax.swing.JTextField();
        vLabel = new javax.swing.JLabel();
        vInput = new javax.swing.JTextField();
        sLabel = new javax.swing.JLabel();
        sInput = new javax.swing.JTextField();
        rLabel = new javax.swing.JLabel();
        rInput = new javax.swing.JTextField();
        dLabel = new javax.swing.JLabel();
        dInput = new javax.swing.JTextField();
        cLabel = new javax.swing.JLabel();
        cInput = new javax.swing.JTextField();
        eLabel = new javax.swing.JLabel();
        eInput = new javax.swing.JTextField();
        nLabel = new javax.swing.JLabel();
        nInput = new javax.swing.JTextField();
        aLabel = new javax.swing.JLabel();
        aInput = new javax.swing.JTextField();
        pLabel = new javax.swing.JLabel();
        pInput = new javax.swing.JTextField();
        xLabel = new javax.swing.JLabel();
        xInput = new javax.swing.JTextField();
        bLabel = new javax.swing.JLabel();
        bInput = new javax.swing.JTextField();
        oLabel = new javax.swing.JLabel();
        oInput = new javax.swing.JTextField();
        zLabel = new javax.swing.JLabel();
        zInput = new javax.swing.JTextField();
        kLabel = new javax.swing.JLabel();
        kInput = new javax.swing.JTextField();
        fLabel = new javax.swing.JLabel();
        fInput = new javax.swing.JTextField();
        wLabel = new javax.swing.JLabel();
        wInput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        gap2 = new javax.swing.JLabel();
        jumlahAtas = new javax.swing.JLabel();
        gap1 = new javax.swing.JLabel();
        jumlahBawah = new javax.swing.JLabel();
        aksiPanel = new javax.swing.JPanel();
        cetakButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setPreferredSize(new java.awt.Dimension(915, 734));

        judulPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        judul.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("PAPI COSTIC MAPPING");

        javax.swing.GroupLayout judulPanelLayout = new javax.swing.GroupLayout(judulPanel);
        judulPanel.setLayout(judulPanelLayout);
        judulPanelLayout.setHorizontalGroup(
                judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(judulPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(judul,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addContainerGap()));
        judulPanelLayout.setVerticalGroup(
                judulPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(judulPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(judul)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        masukanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukan"));
        masukanPanel.setToolTipText("");

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaLabel.setText("Nama");

        namaInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaInput.addKeyListener(
                new KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        namaInputKeyReleased(evt);
                    }
                });

        tglLahirLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tglLahirLabel.setText("Tanggal Lahir");

        tglLahirInput.setDateFormatString("dd MMMM yyyy");
        tglLahirInput.addPropertyChangeListener(
                new java.beans.PropertyChangeListener() {
                    public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        tglLahirInputPropertyChange(evt);
                    }
                });

        tglTesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tglTesLabel.setText("Tanggal Tes");

        tglTesInput.setDateFormatString("dd MMMM yyyy");
        tglTesInput.addPropertyChangeListener(
                new java.beans.PropertyChangeListener() {
                    public void propertyChange(java.beans.PropertyChangeEvent evt) {
                        tglTesInputPropertyChange(evt);
                    }
                });

        pendidikanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pendidikanLabel.setText("Pendidikan Terakhir");

        pendidikanInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pendidikanInput.addKeyListener(
                new KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        pendidikanInputKeyReleased(evt);
                    }
                });

        kelaminLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kelaminLabel.setText("Jenis Kelamin");

        kelaminInput.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        kelaminInput.addActionListener(
                new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        kelaminInputActionPerformed(evt);
                    }
                });

        tujuanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tujuanLabel.setText("Tujuan Pemeriksaan");

        tujuanInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tujuanInput.addKeyListener(
                new KeyAdapter() {
                    @Override
                    public void keyReleased(java.awt.event.KeyEvent evt) {
                        tujuanInputKeyReleased(evt);
                    }
                });

        papiInputPanel.setPreferredSize(new java.awt.Dimension(711, 200));

        gLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gLabel.setText("G");

        gInput.addKeyListener(
                new PapiCosticInputKeyAdapter(gInput, 'g', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        lLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLabel.setText("L");

        lInput.addKeyListener(
                new PapiCosticInputKeyAdapter(lInput, 'l', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        iLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        iLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iLabel.setText("I");

        iInput.addKeyListener(
                new PapiCosticInputKeyAdapter(iInput, 'i', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        tLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLabel.setText("T");

        tInput.addKeyListener(
                new PapiCosticInputKeyAdapter(tInput, 't', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        vLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        vLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLabel.setText("V");

        vInput.addKeyListener(
                new PapiCosticInputKeyAdapter(vInput, 'v', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        sLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabel.setText("S");

        sInput.addKeyListener(
                new PapiCosticInputKeyAdapter(sInput, 's', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        rLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rLabel.setText("R");

        rInput.addKeyListener(
                new PapiCosticInputKeyAdapter(rInput, 'r', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        dLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dLabel.setText("D");

        dInput.addKeyListener(
                new PapiCosticInputKeyAdapter(dInput, 'd', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        cLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cLabel.setText("C");

        cInput.addKeyListener(
                new PapiCosticInputKeyAdapter(cInput, 'c', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        eLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        eLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eLabel.setText("E");

        eInput.addKeyListener(
                new PapiCosticInputKeyAdapter(eInput, 'e', true, papiInputPanel, cetakButton,
                        jumlahAtas));

        nLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nLabel.setText("N");

        nInput.addKeyListener(
                new PapiCosticInputKeyAdapter(nInput, 'n', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        aLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLabel.setText("A");

        aInput.addKeyListener(
                new PapiCosticInputKeyAdapter(aInput, 'a', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        pLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pLabel.setText("P");

        pInput.addKeyListener(
                new PapiCosticInputKeyAdapter(pInput, 'p', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        xLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel.setText("X");

        xInput.addKeyListener(
                new PapiCosticInputKeyAdapter(xInput, 'x', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        bLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bLabel.setText("B");

        bInput.addKeyListener(
                new PapiCosticInputKeyAdapter(bInput, 'b', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        oLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oLabel.setText("O");

        oInput.addKeyListener(
                new PapiCosticInputKeyAdapter(oInput, 'o', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        zLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        zLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        zLabel.setText("Z");

        zInput.addKeyListener(
                new PapiCosticInputKeyAdapter(zInput, 'z', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        kLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kLabel.setText("K");

        kInput.addKeyListener(
                new PapiCosticInputKeyAdapter(kInput, 'k', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        fLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fLabel.setText("F");

        fInput.addKeyListener(
                new PapiCosticInputKeyAdapter(fInput, 'f', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        wLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wLabel.setText("W");

        wInput.addKeyListener(
                new PapiCosticInputKeyAdapter(wInput, 'w', false, papiInputPanel, cetakButton,
                        jumlahBawah));

        javax.swing.GroupLayout papiInputPanelLayout = new javax.swing.GroupLayout(papiInputPanel);
        papiInputPanel.setLayout(papiInputPanelLayout);
        papiInputPanelLayout.setHorizontalGroup(
                papiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(papiInputPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(gLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(gInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(nLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(nInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(lLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(lInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(aLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(aInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(iLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(iInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(pLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(pInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(tInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(tLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(xLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(xInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(vLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(vInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(bLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(bInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(sLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(sInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(oLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(oInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(rLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(rInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(zLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(zInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(dInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(dLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(kLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(kInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(cLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                65, Short.MAX_VALUE)
                                        .addComponent(cInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(fLabel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(fInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                false)
                                        .addComponent(eInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE)
                                        .addComponent(eLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                65,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(wLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                65,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(wInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                0,
                                                Short.MAX_VALUE))
                                .addGap(77, 77, 77)));
        papiInputPanelLayout.setVerticalGroup(
                papiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(papiInputPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(eLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(cLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(dLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(rLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(sLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(vLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(vInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(tLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(iLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(lLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(gLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(gInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(papiInputPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(wLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(wInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(fLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(kLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(kInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(zLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(zInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(oLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(oInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(bLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(xLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(xInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(pLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(aLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(aInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(papiInputPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(nLabel)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nInput,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(74, Short.MAX_VALUE)));

        papiInputContainer.add(papiInputPanel);

        jPanel1.setPreferredSize(new java.awt.Dimension(75, 200));

        gap2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gap2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gap2.setText(" ");

        jumlahAtas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jumlahAtas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahAtas.setText("0");

        gap1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gap1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gap1.setText(" ");

        jumlahBawah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jumlahBawah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahBawah.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gap2,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                65,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlahAtas,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                65,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gap1,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                65,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jumlahBawah,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                65,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(gap2)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahAtas)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gap1)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahBawah)
                                .addContainerGap(76, Short.MAX_VALUE)));

        papiInputContainer.add(jPanel1);

        javax.swing.GroupLayout masukanPanelLayout = new javax.swing.GroupLayout(masukanPanel);
        masukanPanel.setLayout(masukanPanelLayout);
        masukanPanelLayout.setHorizontalGroup(
                masukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(masukanPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(masukanPanelLayout
                                                .createSequentialGroup()
                                                .addComponent(papiInputContainer,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        881,
                                                        Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(masukanPanelLayout
                                                .createSequentialGroup()
                                                .addGroup(masukanPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pendidikanLabel)
                                                        .addComponent(namaLabel)
                                                        .addComponent(tglLahirLabel)
                                                        .addComponent(tglTesLabel)
                                                        .addComponent(kelaminLabel)
                                                        .addComponent(tujuanLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(masukanPanelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(masukanPanelLayout
                                                                .createSequentialGroup()
                                                                .addGroup(masukanPanelLayout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tglTesInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                150,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(kelaminInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                150,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tglLahirInput,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                150,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(masukanPanelLayout
                                                                .createSequentialGroup()
                                                                .addGroup(masukanPanelLayout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(pendidikanInput)
                                                                        .addComponent(namaInput,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(tujuanInput))
                                                                .addContainerGap()))))));
        masukanPanelLayout.setVerticalGroup(
                masukanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(masukanPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namaLabel)
                                        .addComponent(namaInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tglLahirInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tglLahirLabel,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tglTesLabel)
                                        .addComponent(tglTesInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pendidikanLabel)
                                        .addComponent(pendidikanInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(kelaminLabel)
                                        .addComponent(kelaminInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(masukanPanelLayout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tujuanLabel)
                                        .addComponent(tujuanInput,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(papiInputContainer,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        275,
                                        Short.MAX_VALUE)
                                .addContainerGap()));

        namaInput.getAccessibleContext().setAccessibleName("Papi Costic Mapping");

        aksiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Aksi"));
        aksiPanel.setLayout(new java.awt.GridBagLayout());

        cetakButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cetakButton.setText("Cetak");
        cetakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakButtonActionPerformed(evt);
            }
        });
        cetakButton.setEnabled(false);
        aksiPanel.add(cetakButton, new java.awt.GridBagConstraints());

        resetButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        aksiPanel.add(resetButton, new java.awt.GridBagConstraints());

        editButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        aksiPanel.add(editButton, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(judulPanel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(masukanPanel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(aksiPanel,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(judulPanel,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(masukanPanel,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aksiPanel,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        109,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void resetComponentValues() {
        namaInput.setText("");
        tglLahirInput.setDate(null);
        tglTesInput.setDate(null);
        pendidikanInput.setText("");
        kelaminInput.setSelectedIndex(0);
        tujuanInput.setText("");
        gInput.setText("");
        lInput.setText("");
        iInput.setText("");
        tInput.setText("");
        vInput.setText("");
        sInput.setText("");
        rInput.setText("");
        dInput.setText("");
        cInput.setText("");
        eInput.setText("");
        nInput.setText("");
        aInput.setText("");
        pInput.setText("");
        xInput.setText("");
        bInput.setText("");
        oInput.setText("");
        zInput.setText("");
        kInput.setText("");
        fInput.setText("");
        wInput.setText("");
        jumlahAtas.setText("0");
        jumlahBawah.setText("0");
    }

    private void namaInputKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_namaInputKeyReleased
        PapiCosticResource.name = namaInput.getText();
        PapiCosticResource.handleInput(cetakButton);
    }// GEN-LAST:event_namaInputKeyReleased

    private void tglLahirInputPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_tglLahirInputPropertyChange
        PapiCosticResource.birthDate = PapiCosticResource.handleDateInput(tglLahirInput.getDate());
        PapiCosticResource.handleInput(cetakButton);
    }// GEN-LAST:event_tglLahirInputPropertyChange

    private void tglTesInputPropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_tglTesInputPropertyChange
        PapiCosticResource.testDate = PapiCosticResource.handleDateInput(tglTesInput.getDate());
        PapiCosticResource.handleInput(cetakButton);
    }// GEN-LAST:event_tglTesInputPropertyChange

    private void pendidikanInputKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_pendidikanInputKeyReleased
        PapiCosticResource.education = pendidikanInput.getText();
        PapiCosticResource.handleInput(cetakButton);
    }// GEN-LAST:event_pendidikanInputKeyReleased

    private void kelaminInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_kelaminInputActionPerformed
        PapiCosticResource.gender = kelaminInput.getSelectedItem().toString();
        PapiCosticResource.handleInput(cetakButton);
    }// GEN-LAST:event_kelaminInputActionPerformed

    private void tujuanInputKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tujuanInputKeyReleased
        PapiCosticResource.purpose = tujuanInput.getText();
        PapiCosticResource.handleInput(cetakButton);
    }// GEN-LAST:event_tujuanInputKeyReleased

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetButtonActionPerformed
        PapiCosticResource.resetValues();
        resetComponentValues();
        cetakButton.setEnabled(false);
    }// GEN-LAST:event_resetButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_editButtonActionPerformed

    private void cetakButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cetakButtonActionPerformed
        PapiCosticResource.produceReport();
    }// GEN-LAST:event_cetakButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aInput;
    private javax.swing.JLabel aLabel;
    private javax.swing.JPanel aksiPanel;
    private javax.swing.JTextField bInput;
    private javax.swing.JLabel bLabel;
    private javax.swing.JTextField cInput;
    private javax.swing.JLabel cLabel;
    private javax.swing.JButton cetakButton;
    private javax.swing.JTextField dInput;
    private javax.swing.JLabel dLabel;
    private javax.swing.JTextField eInput;
    private javax.swing.JLabel eLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField fInput;
    private javax.swing.JLabel fLabel;
    private javax.swing.JTextField gInput;
    private javax.swing.JLabel gLabel;
    private javax.swing.JLabel gap1;
    private javax.swing.JLabel gap2;
    private javax.swing.JTextField iInput;
    private javax.swing.JLabel iLabel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel judulPanel;
    private javax.swing.JLabel jumlahAtas;
    private javax.swing.JLabel jumlahBawah;
    private javax.swing.JTextField kInput;
    private javax.swing.JLabel kLabel;
    private javax.swing.JComboBox<String> kelaminInput;
    private javax.swing.JLabel kelaminLabel;
    private javax.swing.JTextField lInput;
    private javax.swing.JLabel lLabel;
    private javax.swing.JPanel masukanPanel;
    private javax.swing.JTextField nInput;
    private javax.swing.JLabel nLabel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField oInput;
    private javax.swing.JLabel oLabel;
    private javax.swing.JTextField pInput;
    private javax.swing.JLabel pLabel;
    private javax.swing.JPanel papiInputContainer;
    private javax.swing.JPanel papiInputPanel;
    private javax.swing.JTextField pendidikanInput;
    private javax.swing.JLabel pendidikanLabel;
    private javax.swing.JTextField rInput;
    private javax.swing.JLabel rLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sInput;
    private javax.swing.JLabel sLabel;
    private javax.swing.JTextField tInput;
    private javax.swing.JLabel tLabel;
    private com.toedter.calendar.JDateChooser tglLahirInput;
    private javax.swing.JLabel tglLahirLabel;
    private com.toedter.calendar.JDateChooser tglTesInput;
    private javax.swing.JLabel tglTesLabel;
    private javax.swing.JTextField tujuanInput;
    private javax.swing.JLabel tujuanLabel;
    private javax.swing.JTextField vInput;
    private javax.swing.JLabel vLabel;
    private javax.swing.JTextField wInput;
    private javax.swing.JLabel wLabel;
    private javax.swing.JTextField xInput;
    private javax.swing.JLabel xLabel;
    private javax.swing.JTextField zInput;
    private javax.swing.JLabel zLabel;
    // End of variables declaration//GEN-END:variables
}
