/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package IST;

import IST.resource.IST_ScoreInterpreterV2;
import IST.resource.RubrikCategory;
import java.awt.Color;
import java.awt.Font;
import java.util.LinkedList;
import java.awt.TextArea;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JTextArea;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.ListIterator;
import java.util.Map;
import java.util.NavigableMap;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author nicol
 */
public class ISTEditForm extends javax.swing.JDialog {

    LinkedList<String> tarKecerdasan, berpikirKompreheren, kemAnalisis, dayaIngat, kreativitas, menilai, mengambilKeputusan, berbahasa, coraBerpikir, jenisKecerdasan, fleksibel, angka;
    int startIndex;
    int endIndex;
    JTextArea[] textAreas;
    IST_ScoreInterpreterV2 interpretation;
    String key;
    IST_ScoreInterpreterV2.Range k, ks, c, cMin, cPlus, b, bs;
    

    /**
     * Creates new form test_2
     */
    @SuppressWarnings("empty-statement")
    public ISTEditForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        textAreas = new JTextArea[7];
        interpretation = new IST_ScoreInterpreterV2();
        
        ks = new IST_ScoreInterpreterV2.Range(0, 83.9999);
        k = new IST_ScoreInterpreterV2.Range(84, 89.9999);
        cMin = new IST_ScoreInterpreterV2.Range(90, 98.9999);
        c = new IST_ScoreInterpreterV2.Range(99, 109.9999);
        cPlus = new IST_ScoreInterpreterV2.Range(110, 119.9999);
        b = new IST_ScoreInterpreterV2.Range(120, 129.9999);
        bs = new IST_ScoreInterpreterV2.Range(130, Double.MAX_VALUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        KSScroll = new javax.swing.JScrollPane();
        KSInput = new javax.swing.JTextArea();
        KScroll = new javax.swing.JScrollPane();
        KInput = new javax.swing.JTextArea();
        CMinScroll = new javax.swing.JScrollPane();
        CMinInput = new javax.swing.JTextArea();
        CScroll = new javax.swing.JScrollPane();
        CInput = new javax.swing.JTextArea();
        CPlusScroll = new javax.swing.JScrollPane();
        CPlusInput = new javax.swing.JTextArea();
        BScroll = new javax.swing.JScrollPane();
        BInput = new javax.swing.JTextArea();
        BSScroll = new javax.swing.JScrollPane();
        BSInput = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        simpanbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Taraf Kecerdasan", "Kemampuan berpikir komprehensif", "Kemampuan berpikir fleksibel", "Kemampuan berhitung / mengolah angka", "Daya ingat / konsentrasi", "Kreativitas", "Kemampuan menilai / judgement", "Kemampuan analisis", "Kemampuan mengambil keputusan", "Kemampuan berbahasa", "Cara / corak berpikir", "Jenis kecerdasan" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        KSScroll.setToolTipText("");
        KSScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Kurang Sekali (KS)"));

        KSInput.setColumns(20);
        KSInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KSInput.setLineWrap(true);
        KSInput.setRows(5);
        KSInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        KSScroll.setViewportView(KSInput);

        KScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Kurang (K)"));

        KInput.setColumns(20);
        KInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KInput.setLineWrap(true);
        KInput.setRows(5);
        KInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        KScroll.setViewportView(KInput);

        CMinScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Rata-rata bawah (C-)"));

        CMinInput.setColumns(20);
        CMinInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CMinInput.setLineWrap(true);
        CMinInput.setRows(5);
        CMinInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CMinScroll.setViewportView(CMinInput);

        CScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Rata-rata (C)"));

        CInput.setColumns(20);
        CInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CInput.setLineWrap(true);
        CInput.setRows(5);
        CInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CScroll.setViewportView(CInput);

        CPlusScroll.setToolTipText("");
        CPlusScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Rata-rata atas (C+)"));

        CPlusInput.setColumns(20);
        CPlusInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CPlusInput.setLineWrap(true);
        CPlusInput.setRows(5);
        CPlusInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CPlusScroll.setViewportView(CPlusInput);

        BScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Baik (B)"));

        BInput.setColumns(20);
        BInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BInput.setLineWrap(true);
        BInput.setRows(5);
        BInput.setAutoscrolls(false);
        BInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BScroll.setViewportView(BInput);

        BSScroll.setViewportBorder(javax.swing.BorderFactory.createTitledBorder("Baik Sekali (BS)"));
        BSScroll.setHorizontalScrollBar(null);

        BSInput.setColumns(20);
        BSInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BSInput.setLineWrap(true);
        BSInput.setRows(5);
        BSInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BSScroll.setViewportView(BSInput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(KSScroll, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CMinScroll, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPlusScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BSScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KSScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CMinScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(CScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CPlusScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(BScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(BSScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        simpanbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        simpanbutton.setText("Simpan");
        simpanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(simpanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 375, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 375, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 263, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 263, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        int selected = combobox.getSelectedIndex();

        if (selected == 0) {
            matikan();
            return;
        }

        RubrikCategory selectedCategory = RubrikCategory.values()[selected - 1];
        key = selectedCategory.getLabel();

        if (!key.equals("Jenis kecerdasan")
                || !key.equals("Cara / corak berpikir")
                || !key.equals("Kemampuan berpikir fleksibel")) {

            NavigableMap<IST_ScoreInterpreterV2.Range, String> val = interpretation.getCategoryInterpretation(selectedCategory);
            KSInput.setText(val.get(ks));
            KInput.setText(val.get(k));
            CMinInput.setText(val.get(cMin));
            CInput.setText(val.get(c));
            CPlusInput.setText(val.get(cPlus));
            BInput.setText(val.get(b));
            BSInput.setText(val.get(bs));
        }

    }//GEN-LAST:event_comboboxActionPerformed

    private void simpanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbuttonActionPerformed

    }//GEN-LAST:event_simpanbuttonActionPerformed

    void add2F(LinkedList<String> ll) {
        for (int i = 0; i < ll.size(); i++) {
            try {
                textAreas[i].setText(ll.get(i));
                System.out.println(ll.get(i));
                System.out.println(i + 1);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    void kosong() {
        KSInput.setText("");
        KInput.setText("");
        CMinInput.setText("");
        CInput.setText("");
        CPlusInput.setText("");
        BInput.setText("");
        BSInput.setText("");
    }

    void matikan() {
        for (int i = 0; i < textAreas.length; i++) {
            textAreas[i].setEditable(false);
        }
    }

    void hidupkan() {
        for (int i = 0; i < textAreas.length; i++) {
            textAreas[i].setEditable(true);
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ISTEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ISTEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ISTEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ISTEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ISTEditForm dialog = new ISTEditForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BInput;
    private javax.swing.JTextArea BSInput;
    private javax.swing.JScrollPane BSScroll;
    private javax.swing.JScrollPane BScroll;
    private javax.swing.JTextArea CInput;
    private javax.swing.JTextArea CMinInput;
    private javax.swing.JScrollPane CMinScroll;
    private javax.swing.JTextArea CPlusInput;
    private javax.swing.JScrollPane CPlusScroll;
    private javax.swing.JScrollPane CScroll;
    private javax.swing.JTextArea KInput;
    private javax.swing.JTextArea KSInput;
    private javax.swing.JScrollPane KSScroll;
    private javax.swing.JScrollPane KScroll;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton simpanbutton;
    // End of variables declaration//GEN-END:variables
}
