/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package IST;

import IST.resource.*;
import common.MainFrame;
import common.PasswordDialog;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

import IST.resource.IST_ScoreInterpreter.Result;
import java.io.InputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author nicol
 */
public class ISTForm extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private NormaIST norma;
    private IST_ScoreInterpreterV2 interpreter;

    private List<KomponenPenilaian> nilai = new ArrayList<>();
    private HashMap<String, String> nilaiKategori = new HashMap<>();
    private HashMap<String, Integer> nilaiSW = new HashMap<>();

    public void setNilai(List<KomponenPenilaian> nilai) {
        this.nilai = nilai;
    }
    String charIQ;

    /**
     * Creates new form ist_mapping
     */
    public ISTForm(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        norma = new NormaIST();
        interpreter = new IST_ScoreInterpreterV2();
        initComponents();
        tombolBatal.setEnabled(false);
        tombolHasil.setEnabled(false);
        tombolCetak.setEnabled(false);
        tombolUbah.setEnabled(true);
        setDate();
        resetTable();
    }

    private void setDate() {
        tanggalController.setDate(new Date());
    }

    private void resetTable() {
        nilai = new ArrayList<>();
        try {
            KomponenPenilaianTableModel model = new KomponenPenilaianTableModel(nilai);
            tabelHasil.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal ditampilkan");
        }

        setTableProperties();
    }

    private void setTableProperties() {
//        tabelHasil.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelHasil.getColumnModel().getColumn(0).setPreferredWidth(600);
        tabelHasil.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelHasil.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelHasil.getColumnModel().getColumn(3).setPreferredWidth(1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        masukan = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        SELabel = new javax.swing.JLabel();
        WALabel = new javax.swing.JLabel();
        ANLabel = new javax.swing.JLabel();
        GELabel = new javax.swing.JLabel();
        MELabel = new javax.swing.JLabel();
        RALabel = new javax.swing.JLabel();
        ZRLabel = new javax.swing.JLabel();
        FALabel = new javax.swing.JLabel();
        WULabel = new javax.swing.JLabel();
        FAInput = new javax.swing.JTextField();
        WUInput = new javax.swing.JTextField();
        RAInput = new javax.swing.JTextField();
        ZRInput = new javax.swing.JTextField();
        GEInput = new javax.swing.JTextField();
        MEInput = new javax.swing.JTextField();
        WAInput = new javax.swing.JTextField();
        ANInput = new javax.swing.JTextField();
        SEInput = new javax.swing.JTextField();
        tanggalController = new com.toedter.calendar.JDateChooser();
        namaLabel1 = new javax.swing.JLabel();
        namaLabel2 = new javax.swing.JLabel();
        tgllahirinput = new com.toedter.calendar.JDateChooser();
        controller = new javax.swing.JPanel();
        tombolBatal = new javax.swing.JButton();
        tombolHasil = new javax.swing.JButton();
        tombolCetak = new javax.swing.JButton();
        tombolKeluar = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();

        judul.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IST MAPPING");

        javax.swing.GroupLayout judulLayout = new javax.swing.GroupLayout(judul);
        judul.setLayout(judulLayout);
        judulLayout.setHorizontalGroup(
            judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(judulLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        judulLayout.setVerticalGroup(
            judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(judulLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        masukan.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukan"));
        masukan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        namaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaLabel.setText("Nama");

        namaInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaInputActionPerformed(evt);
            }
        });
        namaInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                namaInputKeyReleased(evt);
            }
        });

        SELabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SELabel.setText("SE");

        WALabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WALabel.setText("WA");

        ANLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ANLabel.setText("AN");

        GELabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GELabel.setText("GE");

        MELabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MELabel.setText("ME");

        RALabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RALabel.setText("RA");

        ZRLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ZRLabel.setText("ZR");

        FALabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FALabel.setText("FA");

        WULabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WULabel.setText("WU");

        FAInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FAInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FAInputKeyReleased(evt);
            }
        });

        WUInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WUInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WUInputKeyReleased(evt);
            }
        });

        RAInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RAInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RAInputKeyReleased(evt);
            }
        });

        ZRInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ZRInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ZRInputKeyReleased(evt);
            }
        });

        GEInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GEInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GEInputKeyReleased(evt);
            }
        });

        MEInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MEInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MEInputKeyReleased(evt);
            }
        });

        WAInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        WAInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAInputActionPerformed(evt);
            }
        });
        WAInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WAInputKeyReleased(evt);
            }
        });

        ANInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ANInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ANInputKeyReleased(evt);
            }
        });

        SEInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SEInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SEInputKeyReleased(evt);
            }
        });

        tanggalController.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tanggalControllerKeyReleased(evt);
            }
        });

        namaLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaLabel1.setText("Tanggal Tes");

        namaLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namaLabel2.setText("Tanggal lahir");

        tgllahirinput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tgllahirinputKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout masukanLayout = new javax.swing.GroupLayout(masukan);
        masukan.setLayout(masukanLayout);
        masukanLayout.setHorizontalGroup(
            masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukanLayout.createSequentialGroup()
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masukanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLabel1)
                            .addComponent(namaLabel)
                            .addComponent(namaLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalController, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgllahirinput, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(masukanLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(SELabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SEInput, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WALabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ANLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ANInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(WAInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MELabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MEInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(GEInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(masukanLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(RALabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masukanLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ZRLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ZRInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(RAInput, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WULabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WUInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(FAInput, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        masukanLayout.setVerticalGroup(
            masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgllahirinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalController, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FAInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FALabel)
                    .addComponent(RAInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RALabel)
                    .addComponent(GEInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GELabel)
                    .addComponent(WAInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WALabel))
                .addGap(7, 7, 7)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WUInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WULabel)
                    .addComponent(ZRInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZRLabel)
                    .addComponent(MEInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MELabel)
                    .addComponent(ANInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANLabel)
                    .addComponent(SEInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SELabel))
                .addGap(10, 10, 10))
        );

        controller.setBorder(javax.swing.BorderFactory.createTitledBorder("Aksi"));

        tombolBatal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolBatal.setText("Batal");
        tombolBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalActionPerformed(evt);
            }
        });

        tombolHasil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolHasil.setText("Hasil");
        tombolHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHasilActionPerformed(evt);
            }
        });

        tombolCetak.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolCetak.setText("Cetak");
        tombolCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCetakActionPerformed(evt);
            }
        });

        tombolKeluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolKeluar.setText("kembali");
        tombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKeluarActionPerformed(evt);
            }
        });

        tombolUbah.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolUbah.setText("Ubah");
        tombolUbah.setMaximumSize(new java.awt.Dimension(78, 31));
        tombolUbah.setMinimumSize(new java.awt.Dimension(78, 31));
        tombolUbah.setPreferredSize(new java.awt.Dimension(78, 31));
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controllerLayout = new javax.swing.GroupLayout(controller);
        controller.setLayout(controllerLayout);
        controllerLayout.setHorizontalGroup(
            controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controllerLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(tombolBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        controllerLayout.setVerticalGroup(
            controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controllerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tombolBatal)
                        .addComponent(tombolHasil)
                        .addComponent(tombolCetak)
                        .addComponent(tombolKeluar))
                    .addComponent(tombolUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tabelHasil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabelHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Variabel", "Nilai", "Kategori", "Deskripsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelHasil.setToolTipText("");
        tabelHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelHasil.setRowHeight(30);
        tabelHasil.setShowHorizontalLines(true);
        tabelHasil.setShowVerticalLines(true);
        tabelHasil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tabelHasilMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(tabelHasil);
        if (tabelHasil.getColumnModel().getColumnCount() > 0) {
            tabelHasil.getColumnModel().getColumn(0).setResizable(false);
            tabelHasil.getColumnModel().getColumn(1).setResizable(false);
            tabelHasil.getColumnModel().getColumn(2).setResizable(false);
            tabelHasil.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(judul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(masukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namaInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namaInputKeyReleased
        perbaruiStatusTombol();
    }//GEN-LAST:event_namaInputKeyReleased

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        tgllahirinput.setDate(null);
        setDate();
        clearAllComp();
        resetTable();
        tombolHasil.setEnabled(false);
        tombolBatal.setEnabled(false);
        tombolCetak.setEnabled(false);
    }//GEN-LAST:event_tombolBatalActionPerformed

    private void tombolHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHasilActionPerformed
        try {

            //menampilkan hasil dari input ke dalam tabel
            /**
             * IST Mapping aspek yang dipake pada norma: - AN - FA - GE - ME -
             * RA - SE - WA - WU - ZR - GESAMT (untuk dapetin IQ)
             *
             * keknya perlu bikin input proses masing-masing nilai diatas buat
             * hitung skornya
             *
             * note: - skor jenis kecerdasan dan berpikir fleksibel sama -
             * bagaimana cara dapetin skor sw dari tabel yg terbaru - konversi
             * rw ke sw itu pake umur juga, tapi ga tau pengaruhnya besar atau
             * enggak - tambahan input tanggal
             */
            int age = countAge();
            int rwSE = this.norma.getInterpretation("SE", Integer.parseInt(SEInput.getText()), age);
            int rwWA = this.norma.getInterpretation("WA", Integer.parseInt(WAInput.getText()), age);
            int rwAN = this.norma.getInterpretation("AN", Integer.parseInt(ANInput.getText()), age);
            int swME = this.norma.getInterpretation("ME", Integer.parseInt(MEInput.getText()), age);
            int rwRA = this.norma.getInterpretation("RA", Integer.parseInt(RAInput.getText()), age);
            int rwZR = this.norma.getInterpretation("ZR", Integer.parseInt(ZRInput.getText()), age);
            int rwFA = this.norma.getInterpretation("FA", Integer.parseInt(FAInput.getText()), age);
            int rwWU = this.norma.getInterpretation("WU", Integer.parseInt(WUInput.getText()), age);
            Integer GE = this.norma.getStdScore(Integer.parseInt(GEInput.getText()));
            int swGE = this.norma.getInterpretation("GE", GE, age);

            int rwGESAMT = Integer.parseInt(SEInput.getText())
                    + Integer.parseInt(WAInput.getText())
                    + Integer.parseInt(ANInput.getText())
                    + Integer.parseInt(MEInput.getText())
                    + Integer.parseInt(RAInput.getText())
                    + Integer.parseInt(ZRInput.getText())
                    + Integer.parseInt(FAInput.getText())
                    + Integer.parseInt(WUInput.getText())
                    + Integer.parseInt(GEInput.getText());

            int swGESAMT = this.norma.getInterpretGESAMT("GESAMT", rwGESAMT, age);
            int iq = this.norma.getIqScore(swGESAMT);

            String[] evalKomperehensif = interpreter.getInterpretation(RubrikCategory.BERPIKIR_KOMPREHENSIF, ((double) (swGE + rwFA) /2));
            // evalfleksibel(swGE, rwRA, rwAN, rwZR);
            String[] evalMengolahAngka = interpreter.getInterpretation(RubrikCategory.MENGOLAH_ANGKA, ((double) (rwRA + rwZR) /2));
            String[] evalDayaIngat = interpreter.getInterpretation(RubrikCategory.DAYA_INGAT, (swME));
            String[] evalKreativitas = interpreter.getInterpretation(RubrikCategory.KREATIVITAS, ((double) (rwFA + rwWU) /2));
            String[] evalMenilai = interpreter.getInterpretation(RubrikCategory.TARAF_KECERDASAN, (double) rwSE);
            String[] evalAnalisa = interpreter.getInterpretation(RubrikCategory.ANALISIS, ((double) (rwAN + rwWU) /2));
            String[] evalkeputusan = interpreter.getInterpretation(RubrikCategory.MENGAMBIL_KEPUTUSAN, ((double) (rwSE + rwAN + rwWU + rwRA + rwZR) /5));
            String[] evalBahasa = interpreter.getInterpretation(RubrikCategory.BERBAHASA, ((double) rwWA + rwSE) /2);
            // evalBerpikir(swGE, rwRA, rwAN, rwZR);
            // evalJenisKecerdasan(rwWA, swGE, rwSE, rwAN);
            inputToTabel("Kemampuan berpikir komprehensif", evalKomperehensif[0], evalKomperehensif[1], evalKomperehensif[2]);
            inputToTabel("Kemampuan berhitung / mengolah angka", evalMengolahAngka[0], evalMengolahAngka[1], evalMengolahAngka[2]);
            inputToTabel("Kemampuan daya ingat", evalDayaIngat[0], evalDayaIngat[1], evalDayaIngat[2]);
            inputToTabel("Kemampuan kreativitas", evalKreativitas[0], evalKreativitas[1], evalKreativitas[2]);
            inputToTabel("Kemampuan menilai", evalMenilai[0], evalMenilai[1], evalMenilai[2]);
            inputToTabel("Kemampuan analisa", evalAnalisa[0], evalAnalisa[1], evalAnalisa[2]);
            inputToTabel("Kemampuan mengambil keputusan", evalkeputusan[0], evalkeputusan[1], evalkeputusan[2]);
            inputToTabel("Kemampuan berbahasa", evalBahasa[0], evalBahasa[1], evalBahasa[2]);

            nilaiSW.put("se", rwSE);
            nilaiKategori.put("kuase", kategoriNilai(rwSE));
            nilaiSW.put("wa", rwWA);
            nilaiKategori.put("kuawa", kategoriNilai(rwWA));
            nilaiSW.put("an", rwAN);
            nilaiKategori.put("kuaan", kategoriNilai(rwAN));
            nilaiSW.put("me", swME);
            nilaiKategori.put("kuame", kategoriNilai(swME));
            nilaiSW.put("ra", rwRA);
            nilaiKategori.put("kuara", kategoriNilai(rwRA));
            nilaiSW.put("zr", rwZR);
            nilaiKategori.put("kuazr", kategoriNilai(rwZR));
            nilaiSW.put("fa", rwFA);
            nilaiKategori.put("kuafa", kategoriNilai(rwFA));
            nilaiSW.put("wu", rwWU);
            nilaiKategori.put("kuawu", kategoriNilai(rwWU));
            nilaiSW.put("ge", swGE);
            nilaiKategori.put("kuage", kategoriNilai(swGE));
            nilaiSW.put("iq", iq);
            nilaiKategori.put("charIQ", kategoriNilai(iq));
            nilaiSW.put("jml", rwGESAMT);

            refreshTable();

            tombolCetak.setEnabled(true);
            tombolUbah.setEnabled(true);

            JOptionPane.showMessageDialog(this, "Berhasil");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ada kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_tombolHasilActionPerformed

    void inputToTabel(String aspect, String skor, String kategori, String deskripsi) {
        KomponenPenilaian komponen = new KomponenPenilaian(aspect, skor, kategori, deskripsi);
        this.nilai.add(komponen);

    }

    private void tombolCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCetakActionPerformed
        //Mencetak hasil input ke dalam jasper file
        String fileName = "IST/resource/report/ISTReport.jasper";
        //String fileName = "ist_app/formIST.jasper";
        //String fileName = "ist_app/hasil.jasper";
        //        String outFile = "./Report" + " - " + namaInput.getText() + ".pdf";
        //        String outFile = "C:/FormIST/Report" + " - " + namaInput.getText() + ".pdf";

        SimpleDateFormat originalFormat = new SimpleDateFormat("E MMM dd HH:mm:ss z yyyy");
        String formattedDate = "";
        SimpleDateFormat newFormat = new SimpleDateFormat("dd MMMM yyyy");

        try {
            Date date = originalFormat.parse(tanggalController.getDate().toString());

            formattedDate = newFormat.format(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        Map<String, Object> parameter = new HashMap<String, Object>();

        JRBeanCollectionDataSource studentCollectionDataSource
                = new JRBeanCollectionDataSource(nilai);

        parameter.put("datapenilaian", studentCollectionDataSource);
        parameter.put("nama", namaInput.getText());
        parameter.put("tanggal", formattedDate);

        //tabel rw
        parameter.put("charIQ", charIQ);
        parameter.put("rwse", SEInput.getText());
        parameter.put("rwwa", WAInput.getText());
        parameter.put("rwan", ANInput.getText());
        parameter.put("rwge", GEInput.getText());
        parameter.put("rwme", MEInput.getText());
        parameter.put("rwra", RAInput.getText());
        parameter.put("rwzr", ZRInput.getText());
        parameter.put("rwfa", FAInput.getText());
        parameter.put("rwwu", WUInput.getText());

        //tabel sw
        parameter.put("swse", nilaiSW.get("se").toString());
        parameter.put("swwa", nilaiSW.get("wa").toString());
        parameter.put("swan", nilaiSW.get("an").toString());
        parameter.put("swge", nilaiSW.get("ge").toString());
        parameter.put("swme", nilaiSW.get("me").toString());
        parameter.put("swra", nilaiSW.get("ra").toString());
        parameter.put("swzr", nilaiSW.get("zr").toString());
        parameter.put("swfa", nilaiSW.get("fa").toString());
        parameter.put("swwu", nilaiSW.get("wu").toString());
        parameter.put("iq", nilaiSW.get("iq").toString());
        parameter.put("jml", nilaiSW.get("jml").toString());

        //kuawu error
        String[] key = {"kuase", "kuawa", "kuaan", "kuage", "kuame", "kuara", "kuazr", "kuafa", "kuawu", "charIQ"};
        for (int i = 0; i < key.length; i++) {
            System.out.println(key[i] + ": " + nilaiKategori.get(key[i]));
            parameter.put(key[i], nilaiKategori.get(key[i]));
        }

        try {

            InputStream stream = Main.class.getResourceAsStream(fileName);
            JasperPrint jasperPrint = JasperFillManager.fillReport(
                    ClassLoader.getSystemResourceAsStream(fileName), parameter,
                    new JREmptyDataSource());
            JOptionPane.showMessageDialog(this, "Berhasil!");
            bersihkan();
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tombolCetakActionPerformed

    private void tombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKeluarActionPerformed
        //keluar dari panel ist dan kembali ke main
        mainFrame.showCard("MainMenuPanel");
        mainFrame.setTitle("KATEGORISASI MAPPING");
    }//GEN-LAST:event_tombolKeluarActionPerformed

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        PasswordDialog passwordDialog = new PasswordDialog(
                new ISTEditForm(mainFrame, getFocusTraversalKeysEnabled()));
        passwordDialog.showDialog();
    }//GEN-LAST:event_tombolUbahActionPerformed

    private void tabelHasilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelHasilMouseMoved
        // TODO add your handling code here:
        // Set the tooltip to an empty string
        tabelHasil.setToolTipText("");

        // Get the table cell value where the mouse is located
        String value = (String) tabelHasil.getValueAt(tabelHasil.rowAtPoint(evt.getPoint()),
                tabelHasil.columnAtPoint(evt.getPoint()));

        // If the length of the value is greater than some number...
        //        if (value.length() > 50) {
        // add a tooltip to the JTable that shows the value
        tabelHasil.setToolTipText(value);
        //        }
    }//GEN-LAST:event_tabelHasilMouseMoved

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputActionPerformed

    private void tanggalControllerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggalControllerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalControllerKeyReleased

    private void tgllahirinputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgllahirinputKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tgllahirinputKeyReleased

    private void WAInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WAInputKeyReleased
        try {
            if (!WAInput.getText().equals("")) {
                int data = Integer.parseInt(WAInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    WAInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            WAInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_WAInputKeyReleased

    private void GEInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GEInputKeyReleased
        try {
            if (!GEInput.getText().equals("")) {
                int data = Integer.parseInt(GEInput.getText());

                if (data < 0 || data > 31) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 31!", "Error", JOptionPane.ERROR_MESSAGE);
                    GEInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            GEInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_GEInputKeyReleased

    private void RAInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RAInputKeyReleased
        try {
            if (!RAInput.getText().equals("")) {
                int data = Integer.parseInt(RAInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    RAInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            RAInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_RAInputKeyReleased

    private void FAInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FAInputKeyReleased
        try {
            if (!FAInput.getText().equals("")) {
                int data = Integer.parseInt(FAInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    FAInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            FAInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_FAInputKeyReleased

    private void SEInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SEInputKeyReleased
        try {
            if (!SEInput.getText().equals("")) {
                int data = Integer.parseInt(SEInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    SEInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            SEInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_SEInputKeyReleased

    private void ANInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ANInputKeyReleased
        try {
            if (!ANInput.getText().equals("")) {
                int data = Integer.parseInt(ANInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    ANInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            ANInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_ANInputKeyReleased

    private void MEInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MEInputKeyReleased
        try {
            if (!MEInput.getText().equals("")) {
                int data = Integer.parseInt(MEInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    MEInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            MEInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_MEInputKeyReleased

    private void ZRInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ZRInputKeyReleased
        try {
            if (!ZRInput.getText().equals("")) {
                int data = Integer.parseInt(ZRInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                    ZRInput.setText("");
                }
            }
        } catch (NumberFormatException eror) {
            ZRInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_ZRInputKeyReleased

    private void WUInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WUInputKeyReleased
        try {
            if (!WUInput.getText().equals("")) {
                int data = Integer.parseInt(WUInput.getText());

                if (data < 0 || data > 20) {
                    JOptionPane.showMessageDialog(this, "Nilai harus antara 0 dan 20!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException eror) {
            WUInput.setText("");
            JOptionPane.showMessageDialog(this, "Nilai harus angka!", "Error", ERROR_MESSAGE);
        }
        perbaruiStatusTombol();
    }//GEN-LAST:event_WUInputKeyReleased

    private void WAInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAInputActionPerformed

    private void refreshTable() {
        try {
            KomponenPenilaianTableModel model = new KomponenPenilaianTableModel(this.nilai);
            tabelHasil.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal ditampilkan");
        }

        setTableProperties();
    }

    private void clearAllComp() {
        namaInput.setText("");
        setDate();
        SEInput.setText("");
        WAInput.setText("");
        ANInput.setText("");
        GEInput.setText("");
        MEInput.setText("");
        RAInput.setText("");
        ZRInput.setText("");
        FAInput.setText("");
        WUInput.setText("");
        resetTable();
    }

    private boolean semuaInputTerisi() {
        return tgllahirinput.getCalendar() != null
                && tanggalController.getCalendar() != null
                && !namaInput.getText().isEmpty()
                && !ANInput.getText().isEmpty()
                && !FAInput.getText().isEmpty()
                && !GEInput.getText().isEmpty()
                && !MEInput.getText().isEmpty()
                && !RAInput.getText().isEmpty()
                && !SEInput.getText().isEmpty()
                && !WAInput.getText().isEmpty()
                && !WUInput.getText().isEmpty()
                && !ZRInput.getText().isEmpty();
    }

    private boolean semuaInputKosong() {
        return tgllahirinput.getCalendar() == null
                && tanggalController.getCalendar() == null
                && namaInput.getText().isEmpty()
                && ANInput.getText().isEmpty()
                && FAInput.getText().isEmpty()
                && GEInput.getText().isEmpty()
                && MEInput.getText().isEmpty()
                && RAInput.getText().isEmpty()
                && SEInput.getText().isEmpty()
                && WAInput.getText().isEmpty()
                && WUInput.getText().isEmpty()
                && ZRInput.getText().isEmpty();
    }

    private void perbaruiStatusTombol() {
        tombolBatal.setEnabled(!semuaInputKosong());
        tombolHasil.setEnabled(semuaInputTerisi());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ANInput;
    private javax.swing.JLabel ANLabel;
    private javax.swing.JTextField FAInput;
    private javax.swing.JLabel FALabel;
    private javax.swing.JTextField GEInput;
    private javax.swing.JLabel GELabel;
    private javax.swing.JTextField MEInput;
    private javax.swing.JLabel MELabel;
    private javax.swing.JTextField RAInput;
    private javax.swing.JLabel RALabel;
    private javax.swing.JTextField SEInput;
    private javax.swing.JLabel SELabel;
    private javax.swing.JTextField WAInput;
    private javax.swing.JLabel WALabel;
    private javax.swing.JTextField WUInput;
    private javax.swing.JLabel WULabel;
    private javax.swing.JTextField ZRInput;
    private javax.swing.JLabel ZRLabel;
    private javax.swing.JPanel controller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel judul;
    private javax.swing.JPanel masukan;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel1;
    private javax.swing.JLabel namaLabel2;
    private javax.swing.JTable tabelHasil;
    private com.toedter.calendar.JDateChooser tanggalController;
    private com.toedter.calendar.JDateChooser tgllahirinput;
    private javax.swing.JButton tombolBatal;
    private javax.swing.JButton tombolCetak;
    private javax.swing.JButton tombolHasil;
    private javax.swing.JButton tombolKeluar;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables

    private void bersihkan() {
        resetTable();
        tombolBatal.setEnabled(false);
        tombolHasil.setEnabled(false);
        tombolCetak.setEnabled(false);
        namaInput.setText("");
        ANInput.setText("");
        FAInput.setText("");
        GEInput.setText("");
        MEInput.setText("");
        RAInput.setText("");
        SEInput.setText("");
        WAInput.setText("");
        WUInput.setText("");
        ZRInput.setText("");
    }

    String kategoriNilai(double nilai) {
        double[] lowerVal = {0, 84, 90, 99, 110, 120, 130};
        double[] upperVal = {83.9999, 89.9999, 98.9999, 109.9999, 119.9999, 129.9999, Double.MAX_VALUE};
        String[] kategori = {"KS", "K", "C-", "C", "C+", "B", "BS"};

        for (int i = 0; i < lowerVal.length; i++) {
            if (nilai >= lowerVal[i] && nilai <= upperVal[i]) {
                return kategori[i];
            }
        }

        return null;
    }

    private int countAge() {
        Calendar today = Calendar.getInstance();
        today.setTime(tanggalController.getDate());
        Calendar bdate = Calendar.getInstance();
        bdate.setTime(tgllahirinput.getDate());

        int age = today.get(Calendar.YEAR) - bdate.get(Calendar.YEAR);

        if (today.get(Calendar.MONTH) < bdate.get(Calendar.MONTH)
                || (today.get(Calendar.MONTH) == bdate.get(Calendar.MONTH) && today.get(Calendar.DAY_OF_MONTH) < bdate.get(Calendar.DAY_OF_MONTH))) {
            age--;
        }

        return age;
    }
}
