/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package msdt;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.NavigableMap;
import msdt.resource.MSDTCategory;
import msdt.resource.MSDTScoreInterpreter;
import msdt.resource.Pair;

/**
 *
 * @author nicol
 */
public class msdtEditForm extends javax.swing.JDialog {

    private Map<String, String[]> inputCache;

    List<String> first = new ArrayList<>();
    String key;

    /**
     * Creates new form msdtEditForm
     */
    public msdtEditForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inputCache = new HashMap<>();
        turn(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combobox = new javax.swing.JComboBox<>();
        simpanbutton = new javax.swing.JButton();
        tombolBatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dampakDanPengaruh = new javax.swing.JLabel();
        KesadaranBerorganisasi = new javax.swing.JLabel();
        MembangunHubunganKerja = new javax.swing.JLabel();
        MengembangkanOrangLain = new javax.swing.JLabel();
        MengarahkanOrangLain = new javax.swing.JLabel();
        MemimpinKelompok = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dampakNpengaruh = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        kesadaran = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        membangun = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        mengembangkan = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        mengarahkan = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        memimpin = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --", "Deserter", "Compromiser", "Missionary", "Buereaucrat", "Autocrat", "Benevolent Autocrat", "Developer", "Executive" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        simpanbutton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        simpanbutton.setText("Simpan");
        simpanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbuttonActionPerformed(evt);
            }
        });

        tombolBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tombolBatal.setText("Batal");
        tombolBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(tombolBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Aspek Psikologis"));
        jPanel2.setLayout(new java.awt.GridLayout(6, 0));

        dampakDanPengaruh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dampakDanPengaruh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dampakDanPengaruh.setText("Dampak Dan Pengaruh");
        dampakDanPengaruh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(dampakDanPengaruh);

        KesadaranBerorganisasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KesadaranBerorganisasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KesadaranBerorganisasi.setText("Kesadaran Berorganisasi");
        KesadaranBerorganisasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(KesadaranBerorganisasi);

        MembangunHubunganKerja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MembangunHubunganKerja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MembangunHubunganKerja.setText("Membangun Hubungan Kerja");
        MembangunHubunganKerja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(MembangunHubunganKerja);

        MengembangkanOrangLain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MengembangkanOrangLain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MengembangkanOrangLain.setText("mengembangkan Orang Lain");
        MengembangkanOrangLain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(MengembangkanOrangLain);

        MengarahkanOrangLain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MengarahkanOrangLain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MengarahkanOrangLain.setText("Mengarahkan Orang Lain");
        MengarahkanOrangLain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(MengarahkanOrangLain);

        MemimpinKelompok.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MemimpinKelompok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MemimpinKelompok.setText("Memimpin Kelompok");
        MemimpinKelompok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(MemimpinKelompok);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Uraian"));
        jPanel3.setLayout(new java.awt.GridLayout(6, 0));

        dampakNpengaruh.setColumns(20);
        dampakNpengaruh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dampakNpengaruh.setLineWrap(true);
        dampakNpengaruh.setRows(5);
        dampakNpengaruh.setWrapStyleWord(true);
        dampakNpengaruh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dampakNpengaruhKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(dampakNpengaruh);

        jPanel3.add(jScrollPane1);

        kesadaran.setColumns(20);
        kesadaran.setLineWrap(true);
        kesadaran.setRows(5);
        kesadaran.setWrapStyleWord(true);
        kesadaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kesadaranKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(kesadaran);

        jPanel3.add(jScrollPane2);

        membangun.setColumns(20);
        membangun.setLineWrap(true);
        membangun.setRows(5);
        membangun.setWrapStyleWord(true);
        membangun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                membangunKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(membangun);

        jPanel3.add(jScrollPane3);

        mengembangkan.setColumns(20);
        mengembangkan.setLineWrap(true);
        mengembangkan.setRows(5);
        mengembangkan.setWrapStyleWord(true);
        mengembangkan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mengembangkanKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(mengembangkan);

        jPanel3.add(jScrollPane4);

        mengarahkan.setColumns(20);
        mengarahkan.setLineWrap(true);
        mengarahkan.setRows(5);
        mengarahkan.setWrapStyleWord(true);
        mengarahkan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mengarahkanKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(mengarahkan);

        jPanel3.add(jScrollPane5);

        memimpin.setColumns(20);
        memimpin.setLineWrap(true);
        memimpin.setRows(5);
        memimpin.setWrapStyleWord(true);
        memimpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                memimpinKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(memimpin);

        jPanel3.add(jScrollPane6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        int selectedIndex = combobox.getSelectedIndex();
        if (selectedIndex == 0) {
            turn(false);
            clearInputs();
            return;
        }

        clearInputs();
        turn(true);
        MSDTCategory selectedCategory = MSDTCategory.values()[selectedIndex - 1];
        key = selectedCategory.getLabel();
        NavigableMap<String, Pair<String, String>> val = MSDTScoreInterpreter.getInterpretations(key);

        if (loadToCache(key) == false) {
            dampakNpengaruh.setText(val.get("Dampak dan pengaruh").getFirst());
            kesadaran.setText(val.get("Kesadaran berorganisasi").getFirst());
            membangun.setText(val.get("Membangun Hubungan Kerja").getFirst());
            mengembangkan.setText(val.get("Mengembangkan orang lain").getFirst());
            mengarahkan.setText(val.get("Mengarahkan orang lain").getFirst());
            memimpin.setText(val.get("Memimpin kelompok").getFirst());
        }
    }//GEN-LAST:event_comboboxActionPerformed

    private boolean loadToCache(String key) {
        if (inputCache.containsKey(key)) {

            String[] cacheValues = inputCache.get(key);

            dampakNpengaruh.setText(cacheValues[0]);
            kesadaran.setText(cacheValues[1]);
            membangun.setText(cacheValues[2]);
            mengembangkan.setText(cacheValues[3]);
            mengarahkan.setText(cacheValues[4]);
            memimpin.setText(cacheValues[5]);

            return true;
        }

        return false;
    }

    private void saveToCache(String key) {
        String[] cacheValues = new String[7];

        cacheValues[0] = dampakNpengaruh.getText();
        cacheValues[1] = kesadaran.getText();
        cacheValues[2] = membangun.getText();
        cacheValues[3] = mengembangkan.getText();
        cacheValues[4] = dampakNpengaruh.getText();
        cacheValues[5] = memimpin.getText();

        inputCache.put(key, cacheValues);
    }

    private void turn(boolean call) {
        dampakNpengaruh.setEnabled(call);
        kesadaran.setEnabled(call);
        membangun.setEnabled(call);
        mengembangkan.setEnabled(call);
        mengarahkan.setEnabled(call);
        memimpin.setEnabled(call);
    }

    private void clearInputs() {
        dampakNpengaruh.setText("");
        kesadaran.setText("");
        membangun.setText("");
        mengembangkan.setText("");
        mengarahkan.setText("");
        memimpin.setText("");
    }

    /**
     *
     * Deserter Compromiser Missionary Buereaucrat Autocrat Benevolent Autocrat
     * Developer Executive
     *
     */

    private void simpanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbuttonActionPerformed

        if (inputCache.containsKey("Deserter")) {
            MSDTScoreInterpreter.setInterpretation("Deserter", inputCache.get("Deserter"));
        }

        if (inputCache.containsKey("Compromiser")) {
            MSDTScoreInterpreter.setInterpretation("Compromiser", inputCache.get("Compromiser"));
        }

        if (inputCache.containsKey("Missionary")) {
            MSDTScoreInterpreter.setInterpretation("Missionary", inputCache.get("Missionary"));
        }

        if (inputCache.containsKey("Buereaucrat")) {
            MSDTScoreInterpreter.setInterpretation("Buereaucrat", inputCache.get("Buereaucrat"));
        }

        if (inputCache.containsKey("Autocrat")) {
            MSDTScoreInterpreter.setInterpretation("Autocrat", inputCache.get("Autocrat"));
        }

        if (inputCache.containsKey("Benevolent Autocrat")) {
            MSDTScoreInterpreter.setInterpretation("Benevolent Autocrat", inputCache.get("Benevolent Autocrat"));
        }

        if (inputCache.containsKey("Developer")) {
            MSDTScoreInterpreter.setInterpretation("Developer", inputCache.get("Developer"));
        }

        if (inputCache.containsKey("Executive")) {
            MSDTScoreInterpreter.setInterpretation("Executive", inputCache.get("Executive"));
        }

        if (MSDTScoreInterpreter.SaveInterpretationsToFile()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Interpretasi berhasil disimpan", "Berhasil",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Interpretasi gagal disimpan", "Gagal",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        combobox.setSelectedIndex(0);
        turn(false);
        clearInputs();

    }//GEN-LAST:event_simpanbuttonActionPerformed

    private void dampakNpengaruhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dampakNpengaruhKeyReleased
        if (!combobox.getSelectedItem().equals("-- PILIH --")) {
            saveToCache(key);
            return;
        }

        clearInputs();
    }//GEN-LAST:event_dampakNpengaruhKeyReleased

    private void kesadaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kesadaranKeyReleased
        if (!combobox.getSelectedItem().equals("-- PILIH --")) {
            saveToCache(key);
            return;
        }

        clearInputs();
    }//GEN-LAST:event_kesadaranKeyReleased

    private void membangunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_membangunKeyReleased
        if (!combobox.getSelectedItem().equals("-- PILIH --")) {
            saveToCache(key);
            return;
        }

        clearInputs();
    }//GEN-LAST:event_membangunKeyReleased

    private void mengembangkanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mengembangkanKeyReleased
        if (!combobox.getSelectedItem().equals("-- PILIH --")) {
            saveToCache(key);
            return;
        }

        clearInputs();
    }//GEN-LAST:event_mengembangkanKeyReleased

    private void mengarahkanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mengarahkanKeyReleased
        if (!combobox.getSelectedItem().equals("-- PILIH --")) {
            saveToCache(key);
            return;
        }

        clearInputs();
    }//GEN-LAST:event_mengarahkanKeyReleased

    private void memimpinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memimpinKeyReleased
        if (!combobox.getSelectedItem().equals("-- PILIH --")) {
            saveToCache(key);
            return;
        }

        clearInputs();
    }//GEN-LAST:event_memimpinKeyReleased

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        inputCache.remove("Deserter");
        inputCache.remove("Compromiser");
        inputCache.remove("Missionary");
        inputCache.remove("Buereaucrat");
        inputCache.remove("Autocrat");
        inputCache.remove("Benevolent Autocrat");
        inputCache.remove("Developer");
        inputCache.remove("Executive");
        dispose();
    }//GEN-LAST:event_tombolBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(msdtEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(msdtEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(msdtEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(msdtEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                msdtEditForm dialog = new msdtEditForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel KesadaranBerorganisasi;
    private javax.swing.JLabel MembangunHubunganKerja;
    private javax.swing.JLabel MemimpinKelompok;
    private javax.swing.JLabel MengarahkanOrangLain;
    private javax.swing.JLabel MengembangkanOrangLain;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel dampakDanPengaruh;
    private javax.swing.JTextArea dampakNpengaruh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea kesadaran;
    private javax.swing.JTextArea membangun;
    private javax.swing.JTextArea memimpin;
    private javax.swing.JTextArea mengarahkan;
    private javax.swing.JTextArea mengembangkan;
    private javax.swing.JButton simpanbutton;
    private javax.swing.JButton tombolBatal;
    // End of variables declaration//GEN-END:variables
}
